#import "conf.typ": *

#show: setup 

#align(center)[
  #text(20pt, weight: "bold")[Вопросы по ОВА (II семестр)]
  #v(1em)
]

// --- Chapters ---
#include "chapters/01.typ"
#include "chapters/02.typ"
#include "chapters/03.typ"
#include "chapters/04.typ"
#include "chapters/05.typ"
#include "chapters/06.typ"
#include "chapters/07.typ"
#include "chapters/08.typ"
#include "chapters/09.typ"
#include "chapters/10.typ"
#include "chapters/11.typ"
#include "chapters/12.typ"
#include "chapters/13.typ"
#include "chapters/14.typ"
#include "chapters/15.typ"
#include "chapters/16.typ"
#include "chapters/17.typ"
#include "chapters/18.typ"
#include "chapters/19.typ"
#include "chapters/20.typ"
#include "chapters/21.typ"
#include "chapters/22.typ"
#include "chapters/23.typ"
#include "chapters/24.typ"
#include "chapters/25.typ"
#include "chapters/26.typ"
#include "chapters/27.typ"
#include "chapters/28.typ"
#include "chapters/29.typ"
#include "chapters/30.typ"
#include "chapters/31.typ"
#include "chapters/32.typ"
#include "chapters/33.typ"
#include "chapters/34.typ"
#include "chapters/35.typ"
#include "chapters/36.typ"
#include "chapters/37.typ"
#include "chapters/38.typ"
#include "chapters/39.typ"
#include "chapters/40.typ"
#include "chapters/41.typ"
#include "chapters/42.typ"
#include "chapters/43.typ"
#include "chapters/44.typ"
#include "chapters/45.typ"
#include "chapters/46.typ"
#include "chapters/47.typ"
#include "chapters/48.typ"
#include "chapters/49.typ"
#include "chapters/50.typ"
#include "chapters/51.typ"
#include "chapters/52.typ"
#include "chapters/53.typ"
#include "chapters/54.typ"
#include "chapters/55.typ"
#include "chapters/56.typ"
#include "chapters/57.typ"
#include "chapters/58.typ"
#include "chapters/59.typ"
#include "chapters/60.typ"
#include "chapters/68.typ"
#include "chapters/69.typ"
