name: Build PDF
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: ubuntu-latest
    # Используем официальный контейнер Typst напрямую. 
    # Это надежнее, чем искать сторонние "setup" экшены.
    container:
      image: ghcr.io/typst/typst:latest

    steps:
      # 1. Забираем код
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Компилируем
      # Внутри этого контейнера команда 'typst' уже установлена.
      - name: Compile PDF
        run: |
          mkdir -p result
          typst compile FHA/Tickets/typ/main.typ result/FHA.pdf

      # 3. Сохраняем результат
      # Этот шаг выполняется уже на хосте, поэтому используем обычный экшен
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fha-notes
          path: result/FHA.pdf
